/* Header for module nukusupl, generated by p2c 1.21alpha-07.Dec.93 */
#ifndef NUKUSUPL_H
#define NUKUSUPL_H
/* p2c: nukusupl.pas, line 2: 
 * Warning: Unrecognized character 015 in file [247] */


#ifdef NUKUSUPL_G
# define vextern
#else
# define vextern extern
#endif


typedef struct timeV {
/* p2c: nukusupl.pas, line 4:
 * Warning: Unrecognized character 015 in file [247] */
  uchar min, sec, fr;
/* p2c: nukusupl.pas, line 5:
 * Warning: Unrecognized character 015 in file [247] */
} timeV;

/* p2c: nukusupl.pas, line 6:
 * Warning: Unrecognized character 015 in file [247] */
typedef timeV timearray[33];
/* p2c: nukusupl.pas, line 7:
 * Warning: Unrecognized character 015 in file [247] */
typedef uchar VPAge[65536L];
/* p2c: nukusupl.pas, line 8:
 * Warning: Unrecognized character 015 in file [247] */
typedef uchar Vsh[64000L];
/* p2c: nukusupl.pas, line 9:
 * Warning: Unrecognized character 015 in file [247] */
/* p2c: nukusupl.pas, line 10:
 * Warning: Unrecognized character 015 in file [247] */
/* p2c: nukusupl.pas, line 11:
 * Warning: Unrecognized character 015 in file [247] */
typedef uchar t_palette[256][3];
/* p2c: nukusupl.pas, line 12:
 * Warning: Unrecognized character 015 in file [247] */
typedef uchar VirTcolor[200][961];

/* p2c: nukusupl.pas, line 13:
 * Warning: Unrecognized character 015 in file [247] */
/* p2c: nukusupl.pas, line 14:
 * Warning: Unrecognized character 015 in file [247] */
/* p2c: nukusupl.pas, line 15: 
 * Warning: Unrecognized character 015 in file [247] */


vextern Char cdletter;
/* p2c: nukusupl.pas, line 16:
 * Warning: Unrecognized character 015 in file [247] */
vextern uchar *VirVidBuff;
/* p2c: nukusupl.pas, line 17:
 * Warning: Unrecognized character 015 in file [247] */
vextern unsigned short timervar;
/* p2c: nukusupl.pas, line 18:
 * Warning: Unrecognized character 015 in file [247] */
vextern uchar (*VPalette)[3];
/* p2c: nukusupl.pas, line 19:
 * Warning: Unrecognized character 015 in file [247] */
vextern uchar (*VirCol)[961];


/* p2c: nukusupl.pas, line 20:
 * Warning: Unrecognized character 015 in file [247] */
/* p2c: nukusupl.pas, line 21:
 * Warning: Unrecognized character 015 in file [247] */
/* p2c: nukusupl.pas, line 22: 
 * Warning: Unrecognized character 015 in file [247] */
extern long dista PP((long x1, long y1, long x2, long y2));
/* p2c: nukusupl.pas, line 23: 
 * Warning: Unrecognized character 015 in file [247] */
extern boolean At1 PP((int b));
/* p2c: nukusupl.pas, line 24: 
 * Warning: Unrecognized character 015 in file [247] */
extern boolean At2 PP((int b));
/* p2c: nukusupl.pas, line 25: 
 * Warning: Unrecognized character 015 in file [247] */
extern uchar BSA PP((int b));
/* p2c: nukusupl.pas, line 26: 
 * Warning: Unrecognized character 015 in file [247] */
extern Void Seta1 PP((uchar *b));
/* p2c: nukusupl.pas, line 27: 
 * Warning: Unrecognized character 015 in file [247] */
extern Void Seta2 PP((uchar *b));
/* p2c: nukusupl.pas, line 28: 
 * Warning: Unrecognized character 015 in file [247] */
extern Void Bsinc PP((uchar *b));
/* p2c: nukusupl.pas, line 29: 
 * Warning: Unrecognized character 015 in file [247] */
extern Void Bsdec PP((uchar *b));
/* p2c: nukusupl.pas, line 30: 
 * Warning: Unrecognized character 015 in file [247] */
extern Char byte2chr PP((int b));
/* p2c: nukusupl.pas, line 31: 
 * Warning: Unrecognized character 015 in file [247] */
extern Void ReadPcx PP((Char *Name, Anyptr where));
/* p2c: nukusupl.pas, line 32: 
 * Warning: Unrecognized character 015 in file [247] */
extern Void ReadPcxP PP((Char *Name, Anyptr where));
/* p2c: nukusupl.pas, line 33: 
 * Warning: Unrecognized character 015 in file [247] */
extern Void MoveN PP((Anyptr A, Anyptr B, int Cb));
/* p2c: nukusupl.pas, line 34: 
 * Warning: Unrecognized character 015 in file [247] */
extern Void MoveI PP((Anyptr A, Anyptr B, int Cb));
/* p2c: nukusupl.pas, line 35: 
 * Warning: Unrecognized character 015 in file [247] */
extern Void Perturb PP((unsigned short *s));
/* p2c: nukusupl.pas, line 36: 
 * Warning: Unrecognized character 015 in file [247] */
extern Void ZBitmap PP((int X, int Y, int xl, int yl, int xt, int yt,
			Anyptr sour));
/* p2c: nukusupl.pas, line 37: 
 * Warning: Unrecognized character 015 in file [247] */
extern Void ZBitmapM PP((Anyptr Sourc, int X, int Y, int xl, int yl, int xt,
			 int yt, Anyptr dest));
/* p2c: nukusupl.pas, line 38: 
 * Warning: Unrecognized character 015 in file [247] */
extern long Givemeallmili PP((long min, long sec, long fr));
/* p2c: nukusupl.pas, line 39: 
 * Warning: Unrecognized character 015 in file [247] */
extern Void File_Error PV();
/* p2c: nukusupl.pas, line 40: 
 * Warning: Unrecognized character 015 in file [247] */
extern boolean Exist PP((Char *FileName));
/* p2c: nukusupl.pas, line 41: 
 * Warning: Unrecognized character 015 in file [247] */
extern Void chekcd PV();
/* p2c: nukusupl.pas, line 42: 
 * Warning: Unrecognized character 015 in file [247] */
extern uchar port PP((int numb));
/* p2c: nukusupl.pas, line 43: 
 * Warning: Unrecognized character 015 in file [247] */
extern Void SetRGB PP((int col, int r, int g, int b));
/* p2c: nukusupl.pas, line 44: 
 * Warning: Unrecognized character 015 in file [247] */
extern unsigned short InvertWord PP((int wo));
/* p2c: nukusupl.pas, line 45: 
 * Warning: Unrecognized character 015 in file [247] */
extern Void MoveWPal PP((Anyptr Source, Anyptr dest, int amount));
/* p2c: nukusupl.pas, line 46: 
 * Warning: Unrecognized character 015 in file [247] */
extern Void SEtClock PP((int Rate));
/* p2c: nukusupl.pas, line 47: 
 * Warning: Unrecognized character 015 in file [247] */
extern Void UpDatePal PV();
/* p2c: nukusupl.pas, line 48: 
 * Warning: Unrecognized character 015 in file [247] */
/* p2c: nukusupl.pas, line 49: 
 * Warning: Unrecognized character 015 in file [247] */
extern Void MovesI PP((Anyptr A, Anyptr B, int Cb));


#undef vextern

#endif /*NUKUSUPL_H*/

/* End. */
